name: Build QEMU
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build
        sudo apt-get install -y libaio-dev libbluetooth-dev libcapstone-dev libbrlapi-dev libbz2-dev
        sudo apt-get install -y libcap-ng-dev libcurl4-gnutls-dev libgtk-3-dev
        sudo apt-get install -y libibverbs-dev libjpeg8-dev libncurses5-dev libnuma-dev
        sudo apt-get install -y librbd-dev librdmacm-dev
        sudo apt-get install -y libsasl2-dev libsdl2-dev libseccomp-dev libsnappy-dev libssh-dev
        sudo apt-get install -y libvde-dev libvdeplug-dev libvte-2.91-dev libxen-dev liblzo2-dev
        sudo apt-get install -y valgrind xfslibs-dev
        sudo apt-get install -y libnfs-dev libiscsi-dev
        sudo apt-get install -y gcc-aarch64-linux-gnu pkg-config
        if [ ! -e /usr/bin/aarch64-linux-gnu-pkg-config ]; then
          sudo ln -sf /usr/share/pkg-config-crosswrapper /usr/bin/aarch64-linux-gnu-pkg-config
        fi

    - name: Build QEMU
      run: |
        mkdir build
        cd build
        ../configure --cpu=aarch64 --cross-prefix=aarch64-linux-gnu- --prefix=$(realpath install) --target-list=i386-softmmu,x86_64-softmmu,i386-linux-user,x86_64-linux-user --static --enable-spice --enable-spice-protocol
        make -j$(nproc --all)
        make install
        mv install ../bruh
        cd ..

    - name: Upload entire QEMU prefix to artifact
      uses: actions/upload-artifact@v3
      with:
        name: QEMU prefix
        path: bruh/*
